itbaima:
  robot:
     username: 3646194183    
     login-type: qr_code 
     protocol: android_watch
     data:
       work-dir: robot-data   #??????????
       cache-dir: cache       #??????????????
       contact-cache: false    #??????????????????????????????????????????????????????????????????????????????????
       save-device-id: true   #??????????????????????????????????????????????