server:
  port: 8014
itbaima:
  robot:
     username: 3646194183
     login-type: password
     password: 136aaa100bbb
     protocol: android_pad
     signer:
       version: 8.9.58               #使用的客户端版本
       url: http://127.0.0.1:8888    #刚刚部署的签名服务器地址
       type: kiliokuara                #使用的签名服务器类型
       authorization-key: kfc        #验证秘钥，默认kfc
       server-identity-key: vivo50   #服务器身份秘钥，默认vivo50
     data:
       work-dir: robot-data
       cache-dir: cache
       contact-cache: false
       save-device-id: true